// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4o3Juge1ORrI8V1Gd5_IA9xN5Nx4qVK0',
    appId: '1:287798398707:web:8b0a7d7d5a62b299fe7186',
    messagingSenderId: '287798398707',
    projectId: 'todo-opcode',
    authDomain: 'todo-opcode.firebaseapp.com',
    storageBucket: 'todo-opcode.appspot.com',
    measurementId: 'G-CSKQJHYGZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKHpx_vimliRgzzohvYMA3I2P7yM-t7N4',
    appId: '1:287798398707:android:2c97147419397da0fe7186',
    messagingSenderId: '287798398707',
    projectId: 'todo-opcode',
    storageBucket: 'todo-opcode.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfKfVHZHmn1TIwylpVzBzl0BuCts-DVIo',
    appId: '1:287798398707:ios:ff62e84215702579fe7186',
    messagingSenderId: '287798398707',
    projectId: 'todo-opcode',
    storageBucket: 'todo-opcode.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfKfVHZHmn1TIwylpVzBzl0BuCts-DVIo',
    appId: '1:287798398707:ios:2678f8c4622417acfe7186',
    messagingSenderId: '287798398707',
    projectId: 'todo-opcode',
    storageBucket: 'todo-opcode.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
